# Generated by Django 5.1.4 on 2024-12-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payments"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payments",
            options={
                "ordering": [
                    "owner",
                    "paid_course",
                    "payment_date",
                    "payment_amount",
                    "payment_method",
                    "session_id",
                    "link",
                ],
                "verbose_name": "Платеж",
                "verbose_name_plural": "Платежи",
            },
        ),
        migrations.AddField(
            model_name="payments",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Укажите Iссылку на оплату",
                max_length=400,
                null=True,
                verbose_name="Ссылка на оплату",
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="session_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите Id сессии",
                max_length=255,
                null=True,
                verbose_name="Id сессии",
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="payment_amount",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Укажите сумму оплаты",
                null=True,
                verbose_name="Сумма оплаты",
            ),
        ),
    ]
